/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/microsoft/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Microsoft Login */
        get: operations["microsoft_login_auth_microsoft_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/microsoft/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Microsoft Callback */
        get: operations["microsoft_callback_auth_microsoft_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/microsoft/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Microsoft Users */
        get: operations["search_microsoft_users_users_microsoft_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/blocked": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Blocked Users */
        get: operations["list_blocked_users_users_blocked_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/blocked/{microsoft_oid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Block User */
        put: operations["block_user_users_blocked__microsoft_oid__put"];
        post?: never;
        /** Unblock User */
        delete: operations["unblock_user_users_blocked__microsoft_oid__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit Role */
        patch: operations["edit_role_users__user_id__role_patch"];
        trace?: never;
    };
    "/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete User */
        delete: operations["delete_user_users__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ticket Requests */
        get: operations["list_ticket_requests_tickets__get"];
        put?: never;
        /** Create Ticket Request */
        post: operations["create_ticket_request_tickets__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Pending Ticket Requests */
        get: operations["list_pending_ticket_requests_tickets_pending_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/spending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Spending */
        get: operations["get_spending_tickets_spending_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/spending/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User Spending */
        get: operations["get_user_spending_tickets_spending_users__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/price-configurations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ticket Price Configurations */
        get: operations["get_ticket_price_configurations_tickets_price_configurations_get"];
        put?: never;
        /** Set Ticket Price */
        post: operations["set_ticket_price_tickets_price_configurations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{ticket_request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ticket Request */
        get: operations["get_ticket_request_tickets__ticket_request_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/pending/{ticket_request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pending Ticket Request */
        get: operations["get_pending_ticket_request_tickets_pending__ticket_request_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{ticket_request_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Ticket Request */
        post: operations["approve_ticket_request_tickets__ticket_request_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{ticket_request_id}/print": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Print Ticket Request */
        get: operations["print_ticket_request_tickets__ticket_request_id__print_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BlockedUserDTO */
        BlockedUserDTO: {
            /** Microsoft Oid */
            microsoft_oid: string;
            /** Email */
            email: string | null;
            /** Name */
            name: string;
            /**
             * Blocked At
             * Format: date-time
             */
            blocked_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MicrosoftUserDTO */
        MicrosoftUserDTO: {
            /** Microsoft Oid */
            microsoft_oid: string;
            /** Email */
            email: string | null;
            /** Name */
            name: string;
            /** Blocked */
            blocked: boolean;
        };
        /** PendingTicketRequestDTO */
        PendingTicketRequestDTO: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Requester Name */
            requester_name: string;
            /** Cantidad */
            cantidad: number;
            /**
             * Fecha Creacion
             * Format: date-time
             */
            fecha_creacion: string;
        };
        /** SpendingRequestDTO */
        SpendingRequestDTO: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Fecha Emision
             * Format: date-time
             */
            fecha_emision: string;
            /** Tickets Emitidos */
            tickets_emitidos: number;
            /** Total Gastado */
            total_gastado: string;
        };
        /** SpendingSummaryDTO */
        SpendingSummaryDTO: {
            /** Period */
            period: string;
            /** Total Gastado */
            total_gastado: string;
            /** Tickets Emitidos */
            tickets_emitidos: number;
            /** Gasto Medio Por Usuario */
            gasto_medio_por_usuario: string;
            /** Usuarios */
            usuarios: components["schemas"]["UserSpendingDTO"][];
        };
        /** TicketPriceConfigurationDTO */
        TicketPriceConfigurationDTO: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Precio Unitario */
            precio_unitario: string;
            /**
             * Updated By Id
             * Format: uuid
             */
            updated_by_id: string;
            /** Updated By Name */
            updated_by_name: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** TicketPriceOverviewDTO */
        TicketPriceOverviewDTO: {
            /** Precio Unitario */
            precio_unitario: string;
            /** Current Configuration Id */
            current_configuration_id: string | null;
            /** Historial */
            historial: components["schemas"]["TicketPriceConfigurationDTO"][];
        };
        /** TicketPriceUpdateDTO */
        TicketPriceUpdateDTO: {
            /** Precio Unitario */
            precio_unitario: number | string;
            /** Expected Configuration Id */
            expected_configuration_id?: string | null;
        };
        /** TicketRequestCreateDTO */
        TicketRequestCreateDTO: {
            /**
             * Cantidad
             * @enum {integer}
             */
            cantidad: 11 | 22;
        };
        /** TicketRequestDTO */
        TicketRequestDTO: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Cantidad */
            cantidad: number;
            /**
             * Created By Id
             * Format: uuid
             */
            created_by_id: string;
            /**
             * Fecha Creacion
             * Format: date-time
             */
            fecha_creacion: string;
            status: components["schemas"]["TicketRequestStatus"];
            /** Approved By Id */
            approved_by_id: string | null;
            /** Approved At */
            approved_at: string | null;
        };
        /**
         * TicketRequestStatus
         * @enum {string}
         */
        TicketRequestStatus: "pending" | "approved" | "rejected";
        /** UserDTO */
        UserDTO: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Name */
            name: string;
            role: components["schemas"]["UserRole"];
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "user" | "approver" | "rrhh" | "accountant";
        /** UserRoleUpdateDTO */
        UserRoleUpdateDTO: {
            role: components["schemas"]["UserRole"];
        };
        /** UserSpendingDTO */
        UserSpendingDTO: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Nombre */
            nombre: string;
            /** Email */
            email: string;
            /** Total Gastado */
            total_gastado: string;
            /** Tickets Emitidos */
            tickets_emitidos: number;
        };
        /** UserSpendingDetailDTO */
        UserSpendingDetailDTO: {
            /** Period */
            period: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Nombre */
            nombre: string;
            /** Email */
            email: string;
            /** Total Gastado */
            total_gastado: string;
            /** Tickets Emitidos */
            tickets_emitidos: number;
            /** Solicitudes */
            solicitudes: components["schemas"]["SpendingRequestDTO"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    microsoft_login_auth_microsoft_login_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    microsoft_callback_auth_microsoft_callback_get: {
        parameters: {
            query?: {
                code?: string | null;
                state?: string | null;
                error?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDTO"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    search_microsoft_users_users_microsoft_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MicrosoftUserDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_blocked_users_users_blocked_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockedUserDTO"][];
                };
            };
        };
    };
    block_user_users_blocked__microsoft_oid__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                microsoft_oid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockedUserDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unblock_user_users_blocked__microsoft_oid__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                microsoft_oid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_role_users__user_id__role_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRoleUpdateDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ticket_requests_tickets__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketRequestDTO"][];
                };
            };
        };
    };
    create_ticket_request_tickets__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketRequestCreateDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketRequestDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pending_ticket_requests_tickets_pending_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingTicketRequestDTO"][];
                };
            };
        };
    };
    get_spending_tickets_spending_get: {
        parameters: {
            query?: {
                period?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpendingSummaryDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_spending_tickets_spending_users__user_id__get: {
        parameters: {
            query?: {
                period?: string | null;
            };
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSpendingDetailDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ticket_price_configurations_tickets_price_configurations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketPriceOverviewDTO"];
                };
            };
        };
    };
    set_ticket_price_tickets_price_configurations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketPriceUpdateDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketPriceConfigurationDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ticket_request_tickets__ticket_request_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketRequestDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pending_ticket_request_tickets_pending__ticket_request_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketRequestDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_ticket_request_tickets__ticket_request_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketRequestDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    print_ticket_request_tickets__ticket_request_id__print_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
