from typing import Protocol
from uuid import UUID

from modules.users.domain.entities.users import BlockedUser, User


class UserRepository(Protocol):
    async def add(self, user: User) -> None: ...

    async def get_by_id(self, user_id: UUID) -> User | None: ...

    async def get_by_microsoft_oid(self, microsoft_oid: str) -> User | None: ...

    async def get_by_email(self, email: str) -> User | None: ...

    async def list_all(self) -> list[User]: ...

    async def update(self, user: User) -> None: ...

    async def delete(self, user_id: UUID) -> None: ...

    async def is_blocked(self, microsoft_oid: str) -> bool: ...

    async def list_blocked(self) -> list[BlockedUser]: ...

    async def upsert_blocked(self, user: BlockedUser) -> None: ...

    async def delete_blocked(self, microsoft_oid: str) -> None: ...
